gems: [
  jekyll-paginate, # 分页插件
  jekyll-sitemap   # 站点地图插件
]

title: 爱丽美博客
email: 514222057@qq.com
#分页每页5个数据
paginate: 5
paginate_path: "blog/page:num"

keywords: 爱丽美博客,个人技术博客,技术博客,爱丽美,个人博客
description: > # this means to ignore newlines until "baseurl:"
  爱丽美博客,一个前端工程师的博客
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yanglimei.com" # the base hostname & protocol for your site
github_username:  ilimei

# Build settings
# markdown: kramdown

#代码高亮
highlight: true
#SASS添加
sass:
  style: compressed
