# Handling Reading
safe:         false
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "rusty shutter"
markdown: rdiscount